Add lxml-html-clean dev dependency
The following error occurs when building the docs, so we must explicitly
include `lxml-html-clean` as a dev dependency until `mkdocs-jupyter` is
updated:

    ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
    Install lxml[html_clean] or lxml_html_clean directly.